In [2]:
import xarray as xr
import numpy as np
import pandas as pd

# Excercises

## Chapter 1 - Data Structures

### 1.1 Data Arrays

create a `DataArray` named "height" from random data `rng.random((180, 360)) * 400`

1. with dimensions named "latitude" and "longitude"

In [3]:
rng = np.random.default_rng(seed=0)
rng

Generator(PCG64) at 0x1CDFDAE51C0

In [7]:
randomArray=rng.random((180,360))*400
randomArray

array([[ 13.54691872,  87.99273786, 159.54868488, ..., 316.35388169,
        385.05054367,  79.52141227],
       [237.64840474, 134.66282006, 283.89118403, ..., 325.11509026,
         98.6911408 , 326.69426325],
       [ 57.35480316, 381.10134378,  39.60799136, ..., 301.58808138,
         50.56225709, 340.2747501 ],
       ...,
       [  7.4337028 , 240.51177602, 191.18102461, ...,   5.96008593,
        270.89763259, 268.92599807],
       [183.88007125, 268.54517733,  17.19731571, ...,  86.68732062,
        256.25922254,  67.89244805],
       [333.9030059 , 298.54710121, 229.92920942, ...,  53.94815534,
         74.78297579, 241.6784466 ]], shape=(180, 360))

In [8]:
height = xr.DataArray(data=randomArray, dims=["latitude", "longitude"])
height

<xarray.DataArray (latitude: 180, longitude: 360)> Size: 518kB
array([[ 13.54691872,  87.99273786, 159.54868488, ..., 316.35388169,
        385.05054367,  79.52141227],
       [237.64840474, 134.66282006, 283.89118403, ..., 325.11509026,
         98.6911408 , 326.69426325],
       [ 57.35480316, 381.10134378,  39.60799136, ..., 301.58808138,
         50.56225709, 340.2747501 ],
       ...,
       [  7.4337028 , 240.51177602, 191.18102461, ...,   5.96008593,
        270.89763259, 268.92599807],
       [183.88007125, 268.54517733,  17.19731571, ...,  86.68732062,
        256.25922254,  67.89244805],
       [333.9030059 , 298.54710121, 229.92920942, ...,  53.94815534,
         74.78297579, 241.6784466 ]], shape=(180, 360))
Dimensions without coordinates: latitude, longitude

2. with dimension coordinates:

    * “latitude”: -90 to 89 with step size 1

    * “longitude”: -180 to 179 with step size 1

In [9]:
np.arange(-90,89,1)

array([-90, -89, -88, -87, -86, -85, -84, -83, -82, -81, -80, -79, -78,
       -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66, -65,
       -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53, -52,
       -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39,
       -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26,
       -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,
         1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88])

In [10]:
height.coords["latitude"]=np.arange(-90,90,1)
height.coords["longitude"]=np.arange(-180, 180, 1)
height

<xarray.DataArray (latitude: 180, longitude: 360)> Size: 518kB
array([[ 13.54691872,  87.99273786, 159.54868488, ..., 316.35388169,
        385.05054367,  79.52141227],
       [237.64840474, 134.66282006, 283.89118403, ..., 325.11509026,
         98.6911408 , 326.69426325],
       [ 57.35480316, 381.10134378,  39.60799136, ..., 301.58808138,
         50.56225709, 340.2747501 ],
       ...,
       [  7.4337028 , 240.51177602, 191.18102461, ...,   5.96008593,
        270.89763259, 268.92599807],
       [183.88007125, 268.54517733,  17.19731571, ...,  86.68732062,
        256.25922254,  67.89244805],
       [333.9030059 , 298.54710121, 229.92920942, ...,  53.94815534,
         74.78297579, 241.6784466 ]], shape=(180, 360))
Coordinates:
  * latitude   (latitude) int64 1kB -90 -89 -88 -87 -86 -85 ... 85 86 87 88 89
  * longitude  (longitude) int64 3kB -180 -179 -178 -177 ... 176 177 178 179

In [12]:
height = xr.DataArray(data=rng.random((180,360))*400, 
                      dims=["latitude","longitude"],
                      coords={"latitude":np.arange(-90,90,1),
                              "longitude":np.arange(-180,180,1)})
height

<xarray.DataArray (latitude: 180, longitude: 360)> Size: 518kB
array([[ 40.06805917, 174.04891567, 374.06146847, ...,   9.68114118,
         66.35682319, 306.5529529 ],
       [ 47.4271886 , 331.09977385, 241.55290813, ..., 259.68020236,
        101.02984943, 196.48732745],
       [ 47.74283359, 103.36367425, 170.59133832, ..., 187.66041918,
        227.78321323, 170.86216527],
       ...,
       [355.44983347, 299.77319695, 389.83365644, ..., 166.16005148,
         20.37022883, 115.26392304],
       [240.18242433, 283.39376583,  16.62495733, ...,  16.09804505,
        310.67828026, 237.68023515],
       [126.08096857, 375.62425208, 371.8489632 , ..., 314.15771867,
        215.40189839,   1.11589661]], shape=(180, 360))
Coordinates:
  * latitude   (latitude) int64 1kB -90 -89 -88 -87 -86 -85 ... 85 86 87 88 89
  * longitude  (longitude) int64 3kB -180 -179 -178 -177 ... 176 177 178 179

3. with metadata for both data and coordinates:

    * height: “type”: “ellipsoid”

    * latitude: “type”: “geodetic”

    * longitude: “prime_meridian”: “greenwich”

In [15]:
height.attrs["height"]="Ellipsoid"
height.attrs["latitude"]="Geodetic"
height.attrs["longitude"]={"prime_meridian":"greenwich"}
height

<xarray.DataArray (latitude: 180, longitude: 360)> Size: 518kB
array([[ 40.06805917, 174.04891567, 374.06146847, ...,   9.68114118,
         66.35682319, 306.5529529 ],
       [ 47.4271886 , 331.09977385, 241.55290813, ..., 259.68020236,
        101.02984943, 196.48732745],
       [ 47.74283359, 103.36367425, 170.59133832, ..., 187.66041918,
        227.78321323, 170.86216527],
       ...,
       [355.44983347, 299.77319695, 389.83365644, ..., 166.16005148,
         20.37022883, 115.26392304],
       [240.18242433, 283.39376583,  16.62495733, ...,  16.09804505,
        310.67828026, 237.68023515],
       [126.08096857, 375.62425208, 371.8489632 , ..., 314.15771867,
        215.40189839,   1.11589661]], shape=(180, 360))
Coordinates:
  * latitude   (latitude) int64 1kB -90 -89 -88 -87 -86 -85 ... 85 86 87 88 89
  * longitude  (longitude) int64 3kB -180 -179 -178 -177 ... 176 177 178 179
Attributes:
    height:     Ellipsoid
    latitude:   Geodetic
    longitude:  {'prime_meridian': 'greenwich'}

In [18]:
height.attrs["longitude"]["prime_meridian"]

'greenwich'

In [20]:
height = xr.DataArray(data=randomArray, 
                      dims=["latitude","longitude"],
                      coords={"latitude":np.arange(-90,90,1),
                              "longitude":np.arange(-180,180,1)},
                      attrs={"height":"Ellipsoid",
                             "latitude":"Geodetic",
                             "longitude":{"prime_meridian":"greenwich"}})
height

<xarray.DataArray (latitude: 180, longitude: 360)> Size: 518kB
array([[ 13.54691872,  87.99273786, 159.54868488, ..., 316.35388169,
        385.05054367,  79.52141227],
       [237.64840474, 134.66282006, 283.89118403, ..., 325.11509026,
         98.6911408 , 326.69426325],
       [ 57.35480316, 381.10134378,  39.60799136, ..., 301.58808138,
         50.56225709, 340.2747501 ],
       ...,
       [  7.4337028 , 240.51177602, 191.18102461, ...,   5.96008593,
        270.89763259, 268.92599807],
       [183.88007125, 268.54517733,  17.19731571, ...,  86.68732062,
        256.25922254,  67.89244805],
       [333.9030059 , 298.54710121, 229.92920942, ...,  53.94815534,
         74.78297579, 241.6784466 ]], shape=(180, 360))
Coordinates:
  * latitude   (latitude) int64 1kB -90 -89 -88 -87 -86 -85 ... 85 86 87 88 89
  * longitude  (longitude) int64 3kB -180 -179 -178 -177 ... 176 177 178 179
Attributes:
    height:     Ellipsoid
    latitude:   Geodetic
    longitude:  {'prime_meridian': 'greenwich'}

### 1.2 Data Sets

In [24]:
height = xr.DataArray(rng.random((180, 360)) * 400, dims=["latitude", "longitude"])
gravity_anomaly = xr.DataArray(rng.random((180, 360)) * 400 - 200, dims=["latitude", "longitude"])

1. create a Dataset with two variables along latitude and longitude: height and gravity_anomaly

In [25]:
ds = xr.Dataset({"height":height, "gravity_anomaly":gravity_anomaly})
ds

<xarray.Dataset> Size: 1MB
Dimensions:          (latitude: 180, longitude: 360)
Dimensions without coordinates: latitude, longitude
Data variables:
    height           (latitude, longitude) float64 518kB 209.7 141.9 ... 301.1
    gravity_anomaly  (latitude, longitude) float64 518kB -124.2 148.6 ... -2.39

In [26]:
xr.Dataset(
    {
        "height": (("latitude", "longitude"), rng.random((180, 360)) * 400),
        "gravity_anomaly": (("latitude", "longitude"), rng.random((180, 360)) * 400 - 200),
    }
)

<xarray.Dataset> Size: 1MB
Dimensions:          (latitude: 180, longitude: 360)
Dimensions without coordinates: latitude, longitude
Data variables:
    height           (latitude, longitude) float64 518kB 24.3 148.5 ... 164.4
    gravity_anomaly  (latitude, longitude) float64 518kB -167.8 29.35 ... -100.1

2. add coordinates to latitude and longitude:

    * latitude: from -90 to 90 with step size 1

    * longitude: from -180 to 180 with step size 1

In [28]:
xr.Dataset(
    {"height":height, "gravity_anomaly":gravity_anomaly},
    coords={"latitude": np.arange(-90,90,1),
            "longitude": np.arange(-180,180,1)},
)

<xarray.Dataset> Size: 1MB
Dimensions:          (latitude: 180, longitude: 360)
Coordinates:
  * latitude         (latitude) int64 1kB -90 -89 -88 -87 -86 ... 85 86 87 88 89
  * longitude        (longitude) int64 3kB -180 -179 -178 -177 ... 177 178 179
Data variables:
    height           (latitude, longitude) float64 518kB 209.7 141.9 ... 301.1
    gravity_anomaly  (latitude, longitude) float64 518kB -124.2 148.6 ... -2.39

In [30]:
ds.coords['latitude']=np.arange(-90,90,1)
ds.coords['longitude']=np.arange(-180,180,1)
ds

<xarray.Dataset> Size: 1MB
Dimensions:          (latitude: 180, longitude: 360)
Coordinates:
  * latitude         (latitude) int64 1kB -90 -89 -88 -87 -86 ... 85 86 87 88 89
  * longitude        (longitude) int64 3kB -180 -179 -178 -177 ... 177 178 179
Data variables:
    height           (latitude, longitude) float64 518kB 209.7 141.9 ... 301.1
    gravity_anomaly  (latitude, longitude) float64 518kB -124.2 148.6 ... -2.39

3. add metadata to coordinates and variables:

    * latitude: “type”: “geodetic”

    * longitude: “prime_meridian”: “greenwich”

    * height: “ellipsoid”: “wgs84”

    * gravity_anomaly: “ellipsoid”: “grs80”

In [31]:
xr.Dataset(
    {"height":height, "gravity_anomaly":gravity_anomaly},
    coords={"latitude": np.arange(-90,90,1),
            "longitude": np.arange(-180,180,1)},
    attrs={'latitude':'geodetic',
           'longitude': {'prime_meridian':'greenwich'},
           'height': {'ellipsoid':'wgs84'},
           'gravity_anomaly':{'ellipsoid':'grs80'}}
)

<xarray.Dataset> Size: 1MB
Dimensions:          (latitude: 180, longitude: 360)
Coordinates:
  * latitude         (latitude) int64 1kB -90 -89 -88 -87 -86 ... 85 86 87 88 89
  * longitude        (longitude) int64 3kB -180 -179 -178 -177 ... 177 178 179
Data variables:
    height           (latitude, longitude) float64 518kB 209.7 141.9 ... 301.1
    gravity_anomaly  (latitude, longitude) float64 518kB -124.2 148.6 ... -2.39
Attributes:
    latitude:         geodetic
    longitude:        {'prime_meridian': 'greenwich'}
    height:           {'ellipsoid': 'wgs84'}
    gravity_anomaly:  {'ellipsoid': 'grs80'}

In [33]:
xr.Dataset(
    {
        "height": (("latitude", "longitude"),  rng.random((180, 360)) * 400, {"ellipsoid": "wgs84"}),
        "gravity_anomaly": (("latitude", "longitude"),  rng.random((180, 360)) * 400 - 200, {"ellipsoid": "grs80"}),
    },
    coords={
        "latitude": ("latitude", np.arange(-90, 90, 1), {"type": "geodetic"}),
        "longitude": ("longitude",np.arange(-180, 180, 1),{"prime_meridian": "greenwich"})},
)

<xarray.Dataset> Size: 1MB
Dimensions:          (latitude: 180, longitude: 360)
Coordinates:
  * latitude         (latitude) int64 1kB -90 -89 -88 -87 -86 ... 85 86 87 88 89
  * longitude        (longitude) int64 3kB -180 -179 -178 -177 ... 177 178 179
Data variables:
    height           (latitude, longitude) float64 518kB 203.7 174.3 ... 42.47
    gravity_anomaly  (latitude, longitude) float64 518kB -44.32 12.27 ... 32.75